version: '2.2'
services:
  elastic:
    image: elasticsearch:8.1.2
    container_name: elastic
    volumes:
      - elastic-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

volumes:
  elastic-volume:
    driver: local

networks:
  elastic:
    driver: bridge