version: "3.9"

services:
  elastic:
    image: elasticsearch:8.1.2
    container_name: elastic
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    env_file: .env
    networks:
        - elastic

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge