import './globals.css'
import { Header } from "@/app/components/Header";
import { SideMenu } from "@/app/components/SideMenu";
import { Inter } from 'next/font/google'
import { PropsWithChildren } from "react";
import cn from 'classnames';
import styles from './layout.module.scss';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={cn(inter.className, styles.layout)}>
        <Header/>
        <SideMenu />
        <main className={styles.content}>{children}</main>        
      </body>
    </html>
  )
}
