version: "3.9"

services:
  sql:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - data:/pgsql.d
    ports:
      - "5432:5432"
    networks:
      - metabase_db
      - postgres
  pgadmin:
      image: dpage/pgadmin4
      restart: always
      env_file: .env
      networks:
        - postgres
      ports:
        - "5050:80"
volumes:
  data:
networks:
  postgres:
    driver: bridge
  metabase_db:
    external: true