version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: mA089p9yhsP*
    volumes:
      - pgsqldata:/pgsql.d
    ports:
      - "5432:5432"
volumes:
  pgsqldata: