name: Web app deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: ./web-app

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install packages
      run: npm ci
    - name: Build app
      run: npm run build --if-present
    - name: Run tests
      run: npm test --if-present
    - name: Deploy
      run: rsync -rav --delete .next public next.config.js package.json package-lock.json ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_APP_DIR }}
    - name: Install packages in remote server
      uses: garygrossgarten/github-action-ssh@0.7.0
      with:
        command: cd ${{ secrets.REMOTE_APP_DIR }} && npm ci
        host: ${{ secrets.SSH_HOST }}
        # Username for authentication.
        username: ${{ secrets.SSH_USER }}
