# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Web app deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: ./web-app

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install packages
      run: npm ci
    - name: Build app
      run: npm run build --if-present
    - name: Run tests
      run: npm test --if-present
    - name: Deploy
      run: rsync -rav --delete . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_APP_DIR }}
