name: Web app deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Registry
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: ./web-app

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    #- name: Clear target dir     
    #  run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'exec bash \-l && cd ${{ secrets.REMOTE_APP_DIR}} && rm -r *'
    #- name: Deploy
    #  run: rsync -rav --delete . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_APP_DIR }}- name: Log in to Docker Hub
    
    - name: Log in to Docker Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ secrets.DOCKER_REGISTRY}}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./web-app
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY}}/${{ secrets.DOCKER_REGISTRY_ID}}/rh-web:latest
  
  release:
    name: Release to server
    needs: push_to_registry
    runs-on: self-hosted

    steps:
      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script_stop: true
          script: bash deploy.sh
    
