name: web-deploy
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    deployment:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web-app
        environment: production
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: Build app
              run: npm ci && npm run build
            - name: Create SSH key
              run: |
                 install -m 600 -D /dev/null ~/.ssh/id_rsa
                 echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                 ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts
              shell: bash
              env:
                SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
            - name: Deploy
              uses: matheusvanzan/sshpass-action@v2
              with:
                host: ${{ secrets.HOST }}
                user: ${{ secrets.USER }}
                pass: ${{ secrets.PASSWORD }}
                run: |
                  rsync -rav --delete . ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.APP_DIR }}
                  ssh ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{ secrets.APP_DIR }} && npm run start"