name: web-deploy
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    deployment:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web-app
        environment: production
        steps:
            - uses: actions/checkout@v4
                with:
                    node-version: '20'
            - name: Build app
                run: npm ci
                run: npm run build
            - name: Create SSH key
                run: |
                    install -m 600 -D /dev/null ~/.ssh/id_rsa
                    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                    ssh-keyscan -H "${{ secrets.HOST }}" > ~/.ssh/known_hosts
                shell: bash
                env:
                  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
                  HOST: ${{secrets.HOST}}
            - name: Deploy with rsync
                run: rsync -rav --delete build/ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.APP_DIR }}
            - name: Start web app
                run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} "cd ${{ secrets.APP_DIR }} && npm run start"