name: web-deploy
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    deployment:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web-app
        environment: production
        steps:
          - uses: actions/checkout@v4
            with:
                node-version: '20'
          - run: npm ci
          - run: npm run build
          - run: npm run start